import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css"; // 引入Bootstrap CSS
import "./globals.css"; // 你自己的全局样式
import BootstrapClient from "@/components/BootstrapClient"; // 引入BootstrapClient组件

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BootstrapClient /> {/* 加载Bootstrap JS */}
        {children}
      </body>
    </html>
  );
}